name = "gemqtt"
version = "0.1.0"

description = "Gleam wrapper of the emqx/emqtt client library"
licences = ["Apache-2.0"]
repository = { type = "github", user = "jhillyerd", repo = "gemqtt" }

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"
gleam_erlang = "~> 0.24"
emqtt = "~> 1.2"

[dev-dependencies]
gleeunit = "~> 1.0"
