name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MQTT_PORT: 41883
    services:
      mqtt:
        image: eclipse-mosquitto:2.0
        ports:
          - 41883:1883
        volumes:
          - ./etc/ci/mosquitto:/mosquitto/config
        options: >-
          --health-cmd "timeout 5 mosquitto_sub -t probe -i probe -E"
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "25.3.2"
          gleam-version: "1.0.0-rc2"
          rebar3-version: "3"
      - run: gleam deps download
      - run: gleam test
      - run: gleam format --check src test
