name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MQTT_PORT: 41883
    steps:
      - uses: actions/checkout@v4

      - name: Install and run mosquitto server
        run: |
          sudo apt install mosquitto mosquitto-clients -y
          /usr/sbin/mosquitto -p $MQTT_PORT &

      - uses: erlef/setup-beam@v1
        with:
          otp-version: "25.3.2"
          gleam-version: "1.0.0-rc2"
          rebar3-version: "3"

      - name: Check MQTT server health
        run: timeout 5 mosquitto_sub -p $MQTT_PORT -t probe -i probe -E

      - run: gleam deps download
      - run: gleam test
      - run: gleam format --check src test
